import { DanellaProjectDetails } from './danella.types';

export const danellaHighSplitDetails: DanellaProjectDetails = {
  projectID: 1,
  asbuiltSubProjectID: 15,
  designSubProjectID: 1,
  redesignSubProjectID: 41,
  customFields: [
    {
      projectSecondaryFieldID: 273,
      projectID: 1,
      fieldDefinitionID: 123,
      fieldName: 'ASBUILT MILES',
      deleted: 0,
      createDate: '0001-01-01T00:00:00',
      userID: 3,
    },
    {
      projectSecondaryFieldID: 274,
      projectID: 1,
      fieldDefinitionID: 124,
      fieldName: 'DESIGN MILES',
      deleted: 0,
      createDate: '0001-01-01T00:00:00',
      userID: 3,
    },
    {
      projectSecondaryFieldID: 272,
      projectID: 1,
      fieldDefinitionID: 61,
      fieldName: 'PROJECT_TYPE',
      deleted: 0,
      createDate: '0001-01-01T00:00:00',
      userID: 3,
    },
    {
      projectSecondaryFieldID: 275,
      projectID: 1,
      fieldDefinitionID: 125,
      fieldName: 'REDESIGN MILES',
      deleted: 0,
      createDate: '0001-01-01T00:00:00',
      userID: 3,
    },
    {
      projectSecondaryFieldID: 278,
      projectID: 1,
      fieldDefinitionID: 126,
      fieldName: 'REDESIGN TIME',
      deleted: 0,
      createDate: '0001-01-01T00:00:00',
      userID: 3,
    },
    {
      projectSecondaryFieldID: 276,
      projectID: 1,
      fieldDefinitionID: 66,
      fieldName: 'SECONDARY ID',
      deleted: 0,
      createDate: '0001-01-01T00:00:00',
      userID: 3,
    },
    {
      projectSecondaryFieldID: 279,
      projectID: 1,
      fieldDefinitionID: 127,
      fieldName: 'TIME SPENT BY VENDOR',
      deleted: 0,
      createDate: '0001-01-01T00:00:00',
      userID: 3,
    },
    {
      projectSecondaryFieldID: 277,
      projectID: 1,
      fieldDefinitionID: 67,
      fieldName: 'WORK REQUEST ID - (Request Id)',
      deleted: 0,
      createDate: '0001-01-01T00:00:00',
      userID: 3,
    },
  ],
};
