import { Member, User } from "../types.d";

export const members: Member[] = [
  {
    user: {
      id: 82313475,
      username: "Pablo Ortega",
      email: "portega@tiresi.mx",
      color: "#0197a7",
      profilePicture: null,
      initials: "PO",
      role: 4,
      custom_role: null,
      last_active: "1713572169297",
      date_joined: "1712074289179",
      date_invited: "1712074025534",
    },
    invited_by: {
      id: 82237767,
      username: "Jorge Diaz",
      color: "#0197a7",
      email: "jdiaz@irazutechnology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 82286406,
      username: "Juan Manuel Changala",
      email: "jchangala@irazutechnology.com",
      color: "#c51162",
      profilePicture: null,
      initials: "JC",
      role: 4,
      custom_role: null,
      last_active: "1715395111813",
      date_joined: "1710159956267",
      date_invited: "1709649306880",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 82278020,
      username: "Andres Rodriguez",
      email: "arodriguez@irazutechnology.com",
      color: "#3e2724",
      profilePicture: null,
      initials: "AR",
      role: 4,
      custom_role: null,
      last_active: "1716502759545",
      date_joined: "1708971615587",
      date_invited: "1708971421602",
    },
    invited_by: {
      id: 82237767,
      username: "Jorge Diaz",
      color: "#0197a7",
      email: "jdiaz@irazutechnology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 82274741,
      username: "francisco leal",
      email: "lifrank170997@gmail.com",
      color: "#1090e0",
      profilePicture: null,
      initials: "FL",
      role: 4,
      custom_role: null,
      last_active: "1714603632422",
      date_joined: "1712447351684",
      date_invited: "1708614156553",
    },
    invited_by: {
      id: 43013189,
      username: "Efrain Camacho",
      color: "#c51162",
      email: "efrain.camacho@bl-technology.com",
      initials: "EC",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 82260357,
      username: "Pablo Pietrobon",
      email: "pablopietrobon.bl@gmail.com",
      color: "#455963",
      profilePicture: null,
      initials: "PP",
      role: 4,
      custom_role: null,
      last_active: "1714339555323",
      date_joined: "1707244372297",
      date_invited: "1707239483496",
    },
    invited_by: {
      id: 43015025,
      username: "Martin Prada",
      color: "#e78845",
      email: "martin.prada@bl-technology.com",
      initials: "MP",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 82254638,
      username: "Jorge Alfonzo",
      email: "jorge.alfonzo@bl-technology.com",
      color: "#4466ff",
      profilePicture: null,
      initials: "JA",
      role: 3,
      custom_role: null,
      last_active: "1733437957788",
      date_joined: "1706629298251",
      date_invited: "1706620287875",
    },
    invited_by: {
      id: 82237767,
      username: "Jorge Diaz",
      color: "#0197a7",
      email: "jdiaz@irazutechnology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 82246537,
      username: "Luis Archila",
      email: "aluis15@hotmail.com",
      color: "#536cfe",
      profilePicture: null,
      initials: "LA",
      role: 4,
      custom_role: null,
      last_active: "1721659080733",
      date_joined: "1705527301169",
      date_invited: "1705341805699",
    },
    invited_by: {
      id: 43015025,
      username: "Martin Prada",
      color: "#e78845",
      email: "martin.prada@bl-technology.com",
      initials: "MP",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 82237767,
      username: "Jorge Diaz",
      email: "jdiaz@irazutechnology.com",
      color: "#0197a7",
      profilePicture: null,
      initials: "JD",
      role: 2,
      custom_role: null,
      last_active: "1733490700630",
      date_joined: "1701457399033",
      date_invited: "1701457279978",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 82235549,
      username: "Sara Bolivar",
      email: "sara.bolivar@bl-technology.com",
      color: "#006063",
      profilePicture: null,
      initials: "SB",
      role: 3,
      custom_role: null,
      last_active: "1733429369807",
      date_joined: "1700585071625",
      date_invited: "1700584639535",
    },
    invited_by: {
      id: 43015025,
      username: "Martin Prada",
      color: "#e78845",
      email: "martin.prada@bl-technology.com",
      initials: "MP",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 82234680,
      username: "Leidy Reyes",
      email: "leidyrzapata@gmail.com",
      color: "#aa2fff",
      profilePicture: null,
      initials: "LR",
      role: 4,
      custom_role: null,
      last_active: "1721387578789",
      date_joined: "1700170246051",
      date_invited: "1700164928086",
    },
    invited_by: {
      id: 43013189,
      username: "Efrain Camacho",
      color: "#c51162",
      email: "efrain.camacho@bl-technology.com",
      initials: "EC",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 82224661,
      username: "Edilmar Leal",
      email: "lealedilmar@gmail.com",
      color: "#006063",
      profilePicture: null,
      initials: "EL",
      role: 4,
      custom_role: null,
      last_active: "1705421213544",
      date_joined: "1697066169029",
      date_invited: "1697034649794",
    },
    invited_by: {
      id: 43013189,
      username: "Efrain Camacho",
      color: "#c51162",
      email: "efrain.camacho@bl-technology.com",
      initials: "EC",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 82224660,
      username: "Elianne Rosillo",
      email: "eliannerosillo@gmail.com",
      color: "#388d3c",
      profilePicture: null,
      initials: "ER",
      role: 4,
      custom_role: null,
      last_active: "1720636909833",
      date_joined: "1697074645643",
      date_invited: "1697034649551",
    },
    invited_by: {
      id: 43013189,
      username: "Efrain Camacho",
      color: "#c51162",
      email: "efrain.camacho@bl-technology.com",
      initials: "EC",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 82224658,
      username: null,
      email: "maricarmenramirezf@gmail.com",
      color: null,
      profilePicture: null,
      initials: "M",
      role: 4,
      custom_role: null,
      last_active: null,
      date_joined: null,
      date_invited: "1697034599477",
    },
    invited_by: {
      id: 43013189,
      username: "Efrain Camacho",
      color: "#c51162",
      email: "efrain.camacho@bl-technology.com",
      initials: "EC",
      profilePicture: null,
      banned_date: null,
      status: "invited",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 82224657,
      username: "Augusto Prada",
      email: "augustoprada@yahoo.com",
      color: "#afb42b",
      profilePicture: null,
      initials: "AP",
      role: 4,
      custom_role: null,
      last_active: "1717103225489",
      date_joined: "1709065870637",
      date_invited: "1697034599258",
    },
    invited_by: {
      id: 43013189,
      username: "Efrain Camacho",
      color: "#c51162",
      email: "efrain.camacho@bl-technology.com",
      initials: "EC",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 82218659,
      username: "Melisa Alvarez",
      email: "melisa.alvarez@bl-technology.com",
      color: "#6e56cf",
      profilePicture: null,
      initials: "MA",
      role: 3,
      custom_role: null,
      last_active: "1733488286760",
      date_joined: "1695675040385",
      date_invited: "1695655011290",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 82216914,
      username: "Cuauhtémoc Tavira Peralta",
      email: "ctavira@irazutechnology.com",
      color: "#795548",
      profilePicture: null,
      initials: "CP",
      role: 4,
      custom_role: null,
      last_active: "1713295318588",
      date_joined: "1695310687081",
      date_invited: "1695208417312",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 82216913,
      username: "CRISTIAN BAUTISTA BAUTISTA",
      email: "cbautista@irazutechnology.com",
      color: "#e65100",
      profilePicture: null,
      initials: "CB",
      role: 4,
      custom_role: null,
      last_active: "1698851292817",
      date_joined: "1695442738290",
      date_invited: "1695208416970",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 82216915,
      username: "Jorge Bautista",
      email: "jabautista@irazutechnology.com",
      color: "#ff4081",
      profilePicture: null,
      initials: "JB",
      role: 4,
      custom_role: null,
      last_active: "1705072634103",
      date_joined: "1695654249754",
      date_invited: "1695208416632",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43623278,
      username: "lisbeth garcia",
      email: "lisbethgarciads@gmail.com",
      color: null,
      profilePicture: null,
      initials: "LG",
      role: 4,
      custom_role: null,
      last_active: "1718818452157",
      date_joined: "1694619993827",
      date_invited: "1694619788794",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 82213491,
      username: "Herney Antonio Suarez Garcia",
      email: "herneysuarez43@gmail.com",
      color: "#ffa727",
      profilePicture: null,
      initials: "HG",
      role: 4,
      custom_role: null,
      last_active: "1726316240322",
      date_joined: "1694619858608",
      date_invited: "1694619786597",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 82212594,
      username: "Elias Veron",
      email: "everon@irazutechnology.com",
      color: "#ff5251",
      profilePicture: null,
      initials: "EV",
      role: 3,
      custom_role: null,
      last_active: "1733491845329",
      date_joined: "1694546036309",
      date_invited: "1694545089269",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 82206060,
      username: "Anais Marrero",
      email: "amarrero@irazutechnology.com",
      color: "#263238",
      profilePicture: null,
      initials: "AM",
      role: 3,
      custom_role: null,
      last_active: "1733493104244",
      date_joined: "1693923554030",
      date_invited: "1693918160396",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 82206059,
      username: "Dielys Gonzalez",
      email: "dgonzalez@irazutechnology.com",
      color: "#1b5e20",
      profilePicture: null,
      initials: "DG",
      role: 3,
      custom_role: null,
      last_active: "1733489320831",
      date_joined: "1693919290188",
      date_invited: "1693918130274",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 82206058,
      username: "Lucas Amaru Castañeda Saulquin",
      email: "lcastaneda@irazutechnology.com",
      color: "#c51162",
      profilePicture: null,
      initials: "LS",
      role: 4,
      custom_role: null,
      last_active: "1725414153005",
      date_joined: "1693919162137",
      date_invited: "1693918101037",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 82206056,
      username: "Ezequiel Fernandez",
      email: "gfernandez@irazutechnology.com",
      color: "#ffa727",
      profilePicture: null,
      initials: "EF",
      role: 4,
      custom_role: null,
      last_active: "1733432445491",
      date_joined: "1693919122514",
      date_invited: "1693918078542",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 67456141,
      username: "Antonio Fernandez",
      email: "antoniofernandezandraos.bl@gmail.com",
      color: "#aa2fff",
      profilePicture: null,
      initials: "AF",
      role: 4,
      custom_role: null,
      last_active: "1715722993426",
      date_joined: "1692721455621",
      date_invited: "1692712597607",
    },
    invited_by: {
      id: 43015025,
      username: "Martin Prada",
      color: "#e78845",
      email: "martin.prada@bl-technology.com",
      initials: "MP",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 67456140,
      username: "M Agustin Vladislavic",
      email: "avladislavic.bl@gmail.com",
      color: "#ff4081",
      profilePicture: null,
      initials: "MV",
      role: 4,
      custom_role: null,
      last_active: "1715355424495",
      date_joined: "1692731204850",
      date_invited: "1692712554446",
    },
    invited_by: {
      id: 43015025,
      username: "Martin Prada",
      color: "#e78845",
      email: "martin.prada@bl-technology.com",
      initials: "MP",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 67456139,
      username: "Lucas Elias",
      email: "bl.lucas.elias@gmail.com",
      color: "#ea80fc",
      profilePicture: null,
      initials: "LE",
      role: 4,
      custom_role: null,
      last_active: "1708443816161",
      date_joined: "1692734565339",
      date_invited: "1692712554235",
    },
    invited_by: {
      id: 43015025,
      username: "Martin Prada",
      color: "#e78845",
      email: "martin.prada@bl-technology.com",
      initials: "MP",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 67433722,
      username: "Joaquin Garcia",
      email: "jgarcia@irazutechnology.com",
      color: "#ea80fc",
      profilePicture: null,
      initials: "JG",
      role: 4,
      custom_role: null,
      last_active: "1716325142220",
      date_joined: "1691756081806",
      date_invited: "1691670240091",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 67433721,
      username: "César Alvarado Mendoza",
      email: "calvarado@irazutechnology.com",
      color: "#afb42b",
      profilePicture: null,
      initials: "CM",
      role: 4,
      custom_role: null,
      last_active: "1729570697816",
      date_joined: "1692204544788",
      date_invited: "1691670239864",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 67433720,
      username: "Edgar López Nicolás",
      email: "elopez@irazutechnology.com",
      color: "#02bcd4",
      profilePicture: null,
      initials: "EN",
      role: 4,
      custom_role: null,
      last_active: "1715627129503",
      date_joined: "1692204535343",
      date_invited: "1691670239579",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 44271343,
      username: "Geronimo Confalonieri",
      email: "geronimo.confalonieri@bl-technology.com",
      color: "#ffa12f",
      profilePicture: null,
      initials: "GC",
      role: 3,
      custom_role: null,
      last_active: "1721407105494",
      date_joined: "1689855740024",
      date_invited: "1689855559945",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 67383924,
      username: "Carlos Marin",
      email: "carlos.marin@bl-technology.com",
      color: "#5f7c8a",
      profilePicture: null,
      initials: "CM",
      role: 3,
      custom_role: null,
      last_active: "1733404964690",
      date_joined: "1689610404482",
      date_invited: "1689601640010",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 67358621,
      username: "Benjamin Gutierrez",
      email: "benjamin.gutierrez@bl-technology.com",
      color: "#04a9f4",
      profilePicture: null,
      initials: "BG",
      role: 3,
      custom_role: null,
      last_active: "1733484344120",
      date_joined: "1688563028596",
      date_invited: "1688556989055",
    },
    invited_by: {
      id: 43015025,
      username: "Martin Prada",
      color: "#e78845",
      email: "martin.prada@bl-technology.com",
      initials: "MP",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 67268197,
      username: "Daniel Bossi",
      email: "dbossi@irazutechnology.com",
      color: "#ea80fc",
      profilePicture: null,
      initials: "DB",
      role: 4,
      custom_role: null,
      last_active: "1686351889825",
      date_joined: "1685124256318",
      date_invited: "1685110506950",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 67268196,
      username: "Gerardo Garcia",
      email: "ggarcia@irazutechnology.com",
      color: "#0197a7",
      profilePicture: null,
      initials: "GG",
      role: 4,
      custom_role: null,
      last_active: "1711510619434",
      date_joined: "1685124350022",
      date_invited: "1685110506764",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 67268195,
      username: "Diego Zabala",
      email: "dzabala@irazutechnology.com",
      color: "#e65100",
      profilePicture: null,
      initials: "DZ",
      role: 4,
      custom_role: null,
      last_active: "1718168693187",
      date_joined: "1685453410692",
      date_invited: "1685110506563",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 67268194,
      username: "Juan Guzman",
      email: "jguzman@irazutechnology.com",
      color: "#795548",
      profilePicture: null,
      initials: "JG",
      role: 4,
      custom_role: null,
      last_active: "1685126474873",
      date_joined: "1685126457984",
      date_invited: "1685110506396",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 67268193,
      username: "Esteban Del Monaco",
      email: "edelmonaco@irazutechnology.com",
      color: "#02579b",
      profilePicture: null,
      initials: "EM",
      role: 4,
      custom_role: null,
      last_active: "1686347670685",
      date_joined: "1685126149034",
      date_invited: "1685110505919",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 67239138,
      username: "Jose Morillo",
      email: "jmorillo@irazutechnology.com",
      color: "#ffa727",
      profilePicture: null,
      initials: "JM",
      role: 4,
      custom_role: null,
      last_active: "1717086574848",
      date_joined: "1683654661552",
      date_invited: "1683654357515",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 72173075,
      username: "Mauricio Reyes",
      email: "mreyesw@gmail.com",
      color: "#08c7e0",
      profilePicture: null,
      initials: "MR",
      role: 4,
      custom_role: null,
      last_active: "1682546585182",
      date_joined: "1682102111855",
      date_invited: "1682101202231",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 67209289,
      username: "Joselline Lopez",
      email: "joselin.lopez@chirripocommunications.com",
      color: "#ff897f",
      profilePicture: null,
      initials: "JL",
      role: 4,
      custom_role: null,
      last_active: "1688768366945",
      date_joined: "1681994611080",
      date_invited: "1681924362493",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 67207718,
      username: "Elias Ezequiel Negrette",
      email: "elias.negrette@bl-technology.com",
      color: "#afb42b",
      profilePicture: null,
      initials: "EN",
      role: 3,
      custom_role: null,
      last_active: "1692312327783",
      date_joined: "1681846529745",
      date_invited: "1681846428515",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 61488381,
      username: "Ignacio Alvarado Jimenez",
      email: "ialvarado@chirripocommunications.com",
      color: "#5f7c8a",
      profilePicture: null,
      initials: "IJ",
      role: 4,
      custom_role: null,
      last_active: "1725579043497",
      date_joined: "1680873740863",
      date_invited: "1680866664997",
    },
    invited_by: {
      id: 43015025,
      username: "Martin Prada",
      color: "#e78845",
      email: "martin.prada@bl-technology.com",
      initials: "MP",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 61488380,
      username: "Mauricio Solis",
      email: "mauriciosolischirripodesigncr@gmail.com",
      color: "#ffa727",
      profilePicture: null,
      initials: "MS",
      role: 4,
      custom_role: null,
      last_active: "1706904166628",
      date_joined: "1683044799094",
      date_invited: "1680866467370",
    },
    invited_by: {
      id: 43015025,
      username: "Martin Prada",
      color: "#e78845",
      email: "martin.prada@bl-technology.com",
      initials: "MP",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 61484230,
      username: "Jhoanny Castellanos",
      email: "jhoanny.castellanos@splices.com.ar",
      color: "#006063",
      profilePicture: null,
      initials: "JC",
      role: 4,
      custom_role: null,
      last_active: "1718287533094",
      date_joined: "1680613983178",
      date_invited: "1680613850812",
    },
    invited_by: {
      id: 43015025,
      username: "Martin Prada",
      color: "#e78845",
      email: "martin.prada@bl-technology.com",
      initials: "MP",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 61484228,
      username: "Pastor Liscano",
      email: "pastor.liscano@splices.com.ar",
      color: "#263238",
      profilePicture: null,
      initials: "PL",
      role: 4,
      custom_role: null,
      last_active: "1722029213702",
      date_joined: "1680613969157",
      date_invited: "1680613803757",
    },
    invited_by: {
      id: 43015025,
      username: "Martin Prada",
      color: "#e78845",
      email: "martin.prada@bl-technology.com",
      initials: "MP",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 61482968,
      username: "Ricardo Panameño",
      email: "ricardo.panameno@ccchfc.net",
      color: "#e040fb",
      profilePicture: null,
      initials: "RP",
      role: 4,
      custom_role: null,
      last_active: "1715723940454",
      date_joined: "1680545624625",
      date_invited: "1680545348221",
    },
    invited_by: {
      id: 43015025,
      username: "Martin Prada",
      color: "#e78845",
      email: "martin.prada@bl-technology.com",
      initials: "MP",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 61482965,
      username: "Cecilia Pinto",
      email: "cecilia.pinto@ccchfc.net",
      color: "#d60800",
      profilePicture: null,
      initials: "CP",
      role: 4,
      custom_role: null,
      last_active: "1716998127902",
      date_joined: "1680571137783",
      date_invited: "1680545307986",
    },
    invited_by: {
      id: 43015025,
      username: "Martin Prada",
      color: "#e78845",
      email: "martin.prada@bl-technology.com",
      initials: "MP",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 61482866,
      username: "Diego Panchu",
      email: "diego.panchu@blingenieria.com.ar",
      color: "#81b1ff",
      profilePicture: null,
      initials: "DP",
      role: 4,
      custom_role: null,
      last_active: "1717763368385",
      date_joined: "1680541457507",
      date_invited: "1680540994577",
    },
    invited_by: {
      id: 43015025,
      username: "Martin Prada",
      color: "#e78845",
      email: "martin.prada@bl-technology.com",
      initials: "MP",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 61482822,
      username: "Tomi Nick Fernandez",
      email: "tomi.fernandez@bl-technology.com",
      color: "#5d4037",
      profilePicture: null,
      initials: "TF",
      role: 4,
      custom_role: null,
      last_active: "1722449681813",
      date_joined: "1680637006693",
      date_invited: "1680539469779",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 61482821,
      username: "Julieta Martinotti",
      email: "julieta.martinotti@bl-technology.com",
      color: "#d60800",
      profilePicture: null,
      initials: "JM",
      role: 3,
      custom_role: null,
      last_active: "1733490810392",
      date_joined: "1680711697370",
      date_invited: "1680539445836",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 61462322,
      username: "Francisco Rojas",
      email: "nexusmp@gmail.com",
      color: "#3e2724",
      profilePicture: null,
      initials: "FR",
      role: 4,
      custom_role: null,
      last_active: "1716519992914",
      date_joined: "1679214430338",
      date_invited: "1679214107632",
    },
    invited_by: {
      id: 43015025,
      username: "Martin Prada",
      color: "#e78845",
      email: "martin.prada@bl-technology.com",
      initials: "MP",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 61459705,
      username: "William Claros",
      email: "william.claros@ccchfc.net",
      color: "#b388ff",
      profilePicture: null,
      initials: "WC",
      role: 4,
      custom_role: null,
      last_active: "1723127249264",
      date_joined: "1678986556160",
      date_invited: "1678986381298",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 61459704,
      username: "Rodrigo Torrelio",
      email: "rodrigo.torrelio@blingenieria.com.ar",
      color: "#622aea",
      profilePicture: null,
      initials: "RT",
      role: 4,
      custom_role: null,
      last_active: "1729630184848",
      date_joined: "1678989020129",
      date_invited: "1678986301818",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 18926537,
      username: "Nicolas Abbiati",
      email: "nicolas.abbiati@blingenieria.com.ar",
      color: "#81b1ff",
      profilePicture: null,
      initials: "NA",
      role: 4,
      custom_role: null,
      last_active: "1728436901231",
      date_joined: "1678987295755",
      date_invited: "1678986262613",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 49694392,
      username: "Jorge Diaz Personal",
      email: "93jads@gmail.com",
      color: "#202020",
      profilePicture: null,
      initials: "JP",
      role: 4,
      custom_role: null,
      last_active: "1732622717163",
      date_joined: "1678984772238",
      date_invited: "1678984718741",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 61431895,
      username: "Lucas Aguirre",
      email: "lucas.aguirre@bl-technology.com",
      color: "#8ac34a",
      profilePicture: null,
      initials: "LA",
      role: 3,
      custom_role: null,
      last_active: "1733493576674",
      date_joined: "1677508521932",
      date_invited: "1677508139348",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 61431894,
      username: "María Carolina Guzmán",
      email: "mariac.guzman@bl-technology.com",
      color: "#f57c01",
      profilePicture: null,
      initials: "MG",
      role: 3,
      custom_role: null,
      last_active: "1733492589433",
      date_joined: "1677508582879",
      date_invited: "1677508114173",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 61428443,
      username: "Gandhi Vázquez ortiz",
      email: "gandhivo13@gmail.com",
      color: "#388d3c",
      profilePicture: null,
      initials: "GO",
      role: 4,
      custom_role: null,
      last_active: "1678550894708",
      date_joined: "1677188718820",
      date_invited: "1677163037178",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 61427239,
      username: "Gabriela Ramos",
      email: "gramos7@gmail.com",
      color: null,
      profilePicture: null,
      initials: "GR",
      role: 4,
      custom_role: null,
      last_active: "1678165495395",
      date_joined: "1677180809854",
      date_invited: "1677076988284",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 55526250,
      username: "Mauricio Solis-Chirripo",
      email: "msolis@chirripocommunications.com",
      color: "#304ffe",
      profilePicture: null,
      initials: "MS",
      role: 4,
      custom_role: null,
      last_active: "1691098533951",
      date_joined: "1672952785664",
      date_invited: "1672944300464",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 55522536,
      username: "Nequen Atencio",
      email: "nequen.atencio@bl-technology.com",
      color: "#263238",
      profilePicture: null,
      initials: "NA",
      role: 3,
      custom_role: null,
      last_active: "1733492158010",
      date_joined: "1672840573558",
      date_invited: "1672838781821",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 49788779,
      username: "Zamanta Garcia",
      email: "zamanta.garcia@bl-technology.com",
      color: "#536cfe",
      profilePicture: null,
      initials: "ZG",
      role: 4,
      custom_role: null,
      last_active: "1675702464632",
      date_joined: "1671462432523",
      date_invited: "1671449426473",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 49788777,
      username: "Yamiel Hernandez",
      email: "yamiel.hernandez@bl-technology.com",
      color: "#263238",
      profilePicture: null,
      initials: "YH",
      role: 4,
      custom_role: null,
      last_active: "1701655879803",
      date_joined: "1671465236652",
      date_invited: "1671449420043",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 49788776,
      username: "Alfredo Alfaro",
      email: "alfredo.ramirez@bl-technology.com",
      color: "#aa2fff",
      profilePicture: null,
      initials: "AA",
      role: 4,
      custom_role: null,
      last_active: "1681424493154",
      date_joined: "1671717443325",
      date_invited: "1671449414102",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 49788775,
      username: "Sergio Flores Escalona",
      email: "sergio.flores@bl-technology.com",
      color: "#02579b",
      profilePicture: null,
      initials: "SE",
      role: 4,
      custom_role: null,
      last_active: "1731459816534",
      date_joined: "1671637870375",
      date_invited: "1671449408673",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 49788774,
      username: "Mario Alberto Vázquez Morales",
      email: "mario.vazquez@bl-technology.com",
      color: "#7c4dff",
      profilePicture: null,
      initials: "MM",
      role: 4,
      custom_role: null,
      last_active: "1694487995707",
      date_joined: "1671465564344",
      date_invited: "1671449399337",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 49788773,
      username: "Oscar Felipe Gómez Hernández",
      email: "oscar.gomez@bl-technology.com",
      color: "#02bcd4",
      profilePicture: null,
      initials: "OH",
      role: 4,
      custom_role: null,
      last_active: "1692288730184",
      date_joined: "1671464655600",
      date_invited: "1671449392911",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 49788772,
      username: "Carlos Olaya",
      email: "carlos.olaya@bl-technology.com",
      color: "#f57c01",
      profilePicture: null,
      initials: "CO",
      role: 4,
      custom_role: null,
      last_active: "1701914654857",
      date_joined: "1671637119564",
      date_invited: "1671449387988",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 49788771,
      username: "Rosa Atempa",
      email: "rosa.atempa@bl-technology.com",
      color: "#827718",
      profilePicture: null,
      initials: "RA",
      role: 4,
      custom_role: null,
      last_active: "1725893510115",
      date_joined: "1671465032097",
      date_invited: "1671449357203",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 49735199,
      username: "Venkata Mohan N",
      email: "mvn@ctrl-task.com",
      color: "#cddc39",
      profilePicture: null,
      initials: "VN",
      role: 4,
      custom_role: null,
      last_active: "1703940457923",
      date_joined: "1669381632279",
      date_invited: "1669380095268",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 49735197,
      username: "Paolo Agüero",
      email: "paolo.aguero@chirripocommunications.com",
      color: "#ea80fc",
      profilePicture: null,
      initials: "PA",
      role: 4,
      custom_role: null,
      last_active: "1689096523219",
      date_joined: "1669380481917",
      date_invited: "1669380087782",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 49692418,
      username: "Astrid Garcia Araujo",
      email: "astrid.garcia@bl-technology.com",
      color: "#8077f1",
      profilePicture: null,
      initials: "AA",
      role: 3,
      custom_role: null,
      last_active: "1733489845504",
      date_joined: "1667936081405",
      date_invited: "1667930781660",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 49692417,
      username: "Juan Manuel Changala",
      email: "juan.changala@bl-technology.com",
      color: "#cddc39",
      profilePicture: null,
      initials: "JC",
      role: 4,
      custom_role: null,
      last_active: "1733460050027",
      date_joined: "1667934583887",
      date_invited: "1667930762531",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 49577192,
      username: "Jorge Matamoros Tingo",
      email: "jlmtingo@hotmail.com",
      color: "#ff5251",
      profilePicture: null,
      initials: "JT",
      role: 4,
      custom_role: null,
      last_active: "1688057778484",
      date_joined: "1664547930338",
      date_invited: "1664465081730",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 49577191,
      username: "MOISES ARZOLA VERA",
      email: "marzola@tiresi.mx",
      color: "#c51162",
      profilePicture: null,
      initials: "MV",
      role: 4,
      custom_role: null,
      last_active: "1667002087974",
      date_joined: "1664548602837",
      date_invited: "1664465047118",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43790039,
      username: "Lucas Villalba",
      email: "lucas.villalba@bl-technology.com",
      color: "#5f7c8a",
      profilePicture: null,
      initials: "LV",
      role: 4,
      custom_role: null,
      last_active: "1694101731229",
      date_joined: "1661879458238",
      date_invited: "1661866704767",
    },
    invited_by: {
      id: 43188812,
      username: "Jorge Diaz",
      color: "#d60800",
      email: "jorge.diaz@bl-technology.com",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 55445869,
      username: "Oliver Baker",
      email: "oliver.baker@bl-technology.com",
      color: "#202020",
      profilePicture: null,
      initials: "OB",
      role: 4,
      custom_role: null,
      last_active: "1698265687641",
      date_joined: "1660074854161",
      date_invited: "1660074715402",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43721770,
      username: "Fernando Tavira P",
      email: "fernando.tavira@bl-technology.com",
      color: "#5f7c8a",
      profilePicture: null,
      initials: "FP",
      role: 4,
      custom_role: null,
      last_active: "1731460034111",
      date_joined: "1657915933334",
      date_invited: "1657901236196",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43721769,
      username: "Xavier San Andres",
      email: "x.sanandres@gmail.com",
      color: "#b388ff",
      profilePicture: null,
      initials: "XA",
      role: 4,
      custom_role: null,
      last_active: "1713220343550",
      date_joined: "1657913226683",
      date_invited: "1657901194460",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 42469534,
      username: "Jorge Alberto Bautista ",
      email: "jorgebtaunam05@gmail.com",
      color: null,
      profilePicture: null,
      initials: "JB",
      role: 4,
      custom_role: null,
      last_active: "1732999496811",
      date_joined: "1657644533895",
      date_invited: "1657631559908",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43716800,
      username: "Aracely Martinez",
      email: "saritamart79@gmail.com",
      color: "#827718",
      profilePicture: null,
      initials: "AM",
      role: 4,
      custom_role: null,
      last_active: "1658168742499",
      date_joined: "1657721168551",
      date_invited: "1657631536228",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43716799,
      username: "sofia montiel",
      email: "sofimont88@gmail.com",
      color: "#c51162",
      profilePicture: null,
      initials: "SM",
      role: 4,
      custom_role: null,
      last_active: "1674842824786",
      date_joined: "1657646322448",
      date_invited: "1657631512837",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43685137,
      username: "Caro Alamo",
      email: "carolina.alamo@bl-technology.com",
      color: "#f17ead",
      profilePicture: null,
      initials: "CA",
      role: 3,
      custom_role: null,
      last_active: "1733489513025",
      date_joined: "1655468771506",
      date_invited: "1655468651502",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 43680073,
      username: "Agustina Rojas",
      email: "agustina.rojas@bl-technology.com",
      color: "#f8306d",
      profilePicture: null,
      initials: "AR",
      role: 3,
      custom_role: null,
      last_active: "1733335411933",
      date_joined: "1655385465340",
      date_invited: "1655385435139",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 43681738,
      username: "Jesus Enrique Flores Fierro",
      email: "enrique.flores@bl-technology.com",
      color: "#8ac34a",
      profilePicture: null,
      initials: "JF",
      role: 4,
      custom_role: null,
      last_active: "1733404551421",
      date_joined: "1655249349695",
      date_invited: "1655237639250",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43681162,
      username: "TATIANA ALTAMIRANO",
      email: "taltamiranop@gmail.com",
      color: "#795548",
      profilePicture: null,
      initials: "TA",
      role: 4,
      custom_role: null,
      last_active: "1655572214944",
      date_joined: "1655222787537",
      date_invited: "1655213072495",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43674672,
      username: "- Ailen Silvestri",
      email: "ailensilvestri04@gmail.com",
      color: "#aa2fff",
      profilePicture: null,
      initials: "-S",
      role: 3,
      custom_role: null,
      last_active: "1719320836192",
      date_joined: "1654735832121",
      date_invited: "1654722459798",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 43654977,
      username: "Gabriela Baigorri",
      email: "gabriela.baigorri@bl-technology.com",
      color: "#08c7e0",
      profilePicture: null,
      initials: "GB",
      role: 4,
      custom_role: null,
      last_active: "1715794044269",
      date_joined: "1653486490855",
      date_invited: "1653391559145",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 42399697,
      username: "Jhonny Matos",
      email: "jmatos@tiresi.mx",
      color: "#d60800",
      profilePicture: null,
      initials: "JM",
      role: 4,
      custom_role: null,
      last_active: "1660319857479",
      date_joined: "1653337975234",
      date_invited: "1653337594845",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43640836,
      username: "ROCIO MONSERRAT MONTOYA CELAYA",
      email: "rmontoya@tiresi.mx",
      color: "#aa2fff",
      profilePicture: null,
      initials: "RC",
      role: 4,
      custom_role: null,
      last_active: "1654696065204",
      date_joined: "1652374990633",
      date_invited: "1652367759415",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43640835,
      username: "LEISA ANDREA ZUÑIGA PHILLIPS",
      email: "lzuniga@tiresi.mx",
      color: "#ea80fc",
      profilePicture: null,
      initials: "LP",
      role: 4,
      custom_role: null,
      last_active: "1676050744530",
      date_joined: "1652374989803",
      date_invited: "1652367752146",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43631040,
      username: "Eduardo Mata",
      email: "emata@tiresi.mx",
      color: "#8ac34a",
      profilePicture: null,
      initials: "EM",
      role: 4,
      custom_role: null,
      last_active: "1722381804158",
      date_joined: "1651688215209",
      date_invited: "1651687343101",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43629587,
      username: "Rebeca Grecco",
      email: "rebeca.grecco@splices.com.ar",
      color: "#8ac34a",
      profilePicture: null,
      initials: "RG",
      role: 4,
      custom_role: null,
      last_active: "1662084096552",
      date_joined: "1651666800034",
      date_invited: "1651614702558",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43629585,
      username: "Aníbal Rubin",
      email: "anibal.rubin@splices.com.ar",
      color: "#304ffe",
      profilePicture: null,
      initials: "AR",
      role: 4,
      custom_role: null,
      last_active: "1717120070209",
      date_joined: "1651617180393",
      date_invited: "1651614691699",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43620487,
      username: "Omar Mendez",
      email: "omendez@tiresi.mx",
      color: "#3e2724",
      profilePicture: null,
      initials: "OM",
      role: 4,
      custom_role: null,
      last_active: "1664818419073",
      date_joined: "1651070183166",
      date_invited: "1650978488465",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43620484,
      username: "Juan Salvador Serrano",
      email: "sserrano@tiresi.mx",
      color: "#0197a7",
      profilePicture: null,
      initials: "JS",
      role: 4,
      custom_role: null,
      last_active: "1727407933688",
      date_joined: "1651069819742",
      date_invited: "1650978477465",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43620483,
      username: "Geraldine Puente",
      email: "gpuente@tiresi.mx",
      color: "#e040fb",
      profilePicture: null,
      initials: "GP",
      role: 4,
      custom_role: null,
      last_active: "1652201688478",
      date_joined: "1651068150791",
      date_invited: "1650978456678",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43619639,
      username: "Camila Coronel",
      email: "camila.coronel@bl-technology.com",
      color: "#ff5251",
      profilePicture: null,
      initials: "CC",
      role: 3,
      custom_role: null,
      last_active: "1733321574120",
      date_joined: "1650921041259",
      date_invited: "1650920228845",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 43195399,
      username: "MARIA LISBETH GARCIA",
      email: "lisbethgariz@gmail.com",
      color: "#cddc39",
      profilePicture: null,
      initials: "MG",
      role: 4,
      custom_role: null,
      last_active: "1649727681927",
      date_joined: "1649698295569",
      date_invited: "1649697804446",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43190071,
      username: "Barbara Garcia",
      email: "barbara.garcia@bl-technology.com",
      color: "#ff5251",
      profilePicture:
        "https://attachments.clickup.com/profilePictures/43190071_IdW.jpg",
      initials: "BG",
      role: 3,
      custom_role: null,
      last_active: "1733453783420",
      date_joined: "1649252517586",
      date_invited: "1649252441265",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 43188812,
      username: "Jorge Diaz",
      email: "jorge.diaz@bl-technology.com",
      color: "#d60800",
      profilePicture: null,
      initials: "JD",
      role: 2,
      custom_role: null,
      last_active: "1731632064412",
      date_joined: "1649177217212",
      date_invited: "1649176800264",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 43152416,
      username: "Barbara Baker",
      email: "barbara.baker@bl-technology.com",
      color: "#02579b",
      profilePicture: null,
      initials: "BB",
      role: 4,
      custom_role: null,
      last_active: "1721762433804",
      date_joined: "1649086686273",
      date_invited: "1649086417083",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43178825,
      username: "Andres Rodriguez",
      email: "andres.rodriguez@bl-technology.com",
      color: "#263238",
      profilePicture: null,
      initials: "AR",
      role: 4,
      custom_role: null,
      last_active: "1706881480692",
      date_joined: "1648562326006",
      date_invited: "1648557179520",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43141694,
      username: "Cecilia",
      email: "cecilia.barbosa@bl-technology.com",
      color: "#04a9f4",
      profilePicture: null,
      initials: "C",
      role: 2,
      custom_role: null,
      last_active: "1733443398890",
      date_joined: "1646935589398",
      date_invited: "1646916870726",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 43128671,
      username: "Geronimo Confalonieri",
      email: "geronimo.confalonieri@gmail.com",
      color: "#ff5722",
      profilePicture: null,
      initials: "GC",
      role: 4,
      custom_role: null,
      last_active: "1718718703656",
      date_joined: "1646413074137",
      date_invited: "1646412942979",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43076428,
      username: "Maria Jose Alejos",
      email: "maria.alejos@splices.com.ar",
      color: "#b388ff",
      profilePicture: null,
      initials: "MA",
      role: 4,
      custom_role: null,
      last_active: "1658993356726",
      date_joined: "1644846680041",
      date_invited: "1644501057472",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43076426,
      username: "Mauricio Salazar",
      email: "mauricio.salazar@bl-technology.com",
      color: "#5f7c8a",
      profilePicture: null,
      initials: "MS",
      role: 3,
      custom_role: null,
      last_active: "1729876345305",
      date_joined: "1644501155480",
      date_invited: "1644501030333",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 43076424,
      username: "Nathaly",
      email: "nathalyrossana@gmail.com",
      color: "#c51162",
      profilePicture: null,
      initials: "N",
      role: 4,
      custom_role: null,
      last_active: "1733492689110",
      date_joined: "1644838243645",
      date_invited: "1644501024880",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43076423,
      username: "BEATRIZ LEAL",
      email: "ingbeatrizleal@yahoo.com",
      color: "#304ffe",
      profilePicture: null,
      initials: "BL",
      role: 4,
      custom_role: null,
      last_active: "1733443087871",
      date_joined: "1645726617452",
      date_invited: "1644501018940",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43076422,
      username: "Anais Del Valle Archila Gonzalez",
      email: "ianais09@hotmail.com",
      color: "#263238",
      profilePicture: null,
      initials: "AG",
      role: 4,
      custom_role: null,
      last_active: "1733493514826",
      date_joined: "1645726537024",
      date_invited: "1644501013523",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43076420,
      username: "Rosa María Caballero Solano",
      email: "rosama.caballero.s@gmail.com",
      color: "#006063",
      profilePicture: null,
      initials: "RS",
      role: 4,
      custom_role: null,
      last_active: "1649709122784",
      date_joined: "1644507276924",
      date_invited: "1644501002318",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43076418,
      username: "Martin Barbosa",
      email: "eupipi.tip@gmail.com",
      color: "#0197a7",
      profilePicture: null,
      initials: "MB",
      role: 4,
      custom_role: null,
      last_active: "1716814885619",
      date_joined: "1644591786491",
      date_invited: "1644500994406",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
    can_see_time_spent: true,
    can_see_time_estimated: true,
    can_see_points_estimated: true,
    can_edit_tags: false,
    can_create_views: false,
  },
  {
    user: {
      id: 43076415,
      username: "Cindy Flores",
      email: "cindy.flores@bl-technology.com",
      color: "#ff00fc",
      profilePicture: null,
      initials: "CF",
      role: 3,
      custom_role: null,
      last_active: "1733493952302",
      date_joined: "1645122073448",
      date_invited: "1644500987363",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 43015025,
      username: "Martin Prada",
      email: "martin.prada@bl-technology.com",
      color: "#e78845",
      profilePicture: null,
      initials: "MP",
      role: 3,
      custom_role: null,
      last_active: "1733476103160",
      date_joined: "1642170601906",
      date_invited: "1642170436874",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 43014974,
      username: "Daniela Aranguren",
      email: "daniela.aranguren@bl-technology.com",
      color: "#cddc39",
      profilePicture: null,
      initials: "DA",
      role: 3,
      custom_role: null,
      last_active: "1733447490276",
      date_joined: "1642169897668",
      date_invited: "1642168969928",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 43014971,
      username: "Jean Ramírez",
      email: "jean.ramirez@bl-technology.com",
      color: "#ff897f",
      profilePicture: null,
      initials: "JR",
      role: 3,
      custom_role: null,
      last_active: "1733432021845",
      date_joined: "1644866275645",
      date_invited: "1642168925893",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 43013189,
      username: "Efrain Camacho",
      email: "efrain.camacho@bl-technology.com",
      color: "#c51162",
      profilePicture: null,
      initials: "EC",
      role: 3,
      custom_role: null,
      last_active: "1733400920640",
      date_joined: "1642094657614",
      date_invited: "1642093743144",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 48037984,
      username: "Antonela Yasmin Sarda",
      email: "anto.sarda91@gmail.com",
      color: "#536cfe",
      profilePicture: null,
      initials: "AS",
      role: 3,
      custom_role: null,
      last_active: "1722881813468",
      date_joined: "1635424307414",
      date_invited: "1635185657656",
    },
    invited_by: {
      id: 3174202,
      username: "Jorge Diaz",
      color: "#ea80fc",
      email: "jorge.diaz@blingenieria.com.ar",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 3248466,
      username: "Carlos Salazar",
      email: "carlos.salazar@bl-technology.com",
      color: "#aa2fff",
      profilePicture: null,
      initials: "CS",
      role: 3,
      custom_role: null,
      last_active: "1665621939158",
      date_joined: "1644586653394",
      date_invited: "1624473998447",
    },
    invited_by: {
      id: 3174202,
      username: "Jorge Diaz",
      color: "#ea80fc",
      email: "jorge.diaz@blingenieria.com.ar",
      initials: "JD",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 3174207,
      username: "Julian Di pilla",
      email: "redeshfc94@gmail.com",
      color: "#0197a7",
      profilePicture: null,
      initials: "JP",
      role: 3,
      custom_role: null,
      last_active: "1733451318970",
      date_joined: "1617628424373",
      date_invited: "1617043050319",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 3161572,
      username: "Lautaro Rodriguez",
      email: "lautaro.rodriguez@bl-technology.com",
      color: "#ff4081",
      profilePicture: null,
      initials: "LR",
      role: 3,
      custom_role: null,
      last_active: "1733319887486",
      date_joined: "1615644210523",
      date_invited: "1615594897464",
    },
    invited_by: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      color: "#304ffe",
      email: "diego.barca@blingenieria.com.ar",
      initials: "BI",
      profilePicture: null,
      banned_date: null,
      status: "active",
    },
  },
  {
    user: {
      id: 3011245,
      username: "BL TECHNOLOGY INC",
      email: "diego.barca@blingenieria.com.ar",
      color: "#304ffe",
      profilePicture: null,
      initials: "BI",
      role: 1,
      custom_role: null,
      last_active: "1717444202724",
      date_joined: "1604271967965",
      date_invited: "1604271967965",
    },
  },
];

export function getUser(userId: number): User {
  return members.find((member) => member.user?.id === userId)?.user || {};
}
