export const FIELD_PROJECT_TYPE = 'PROJECT TYPE';

export const FIELD_PREASBUILT_COMPLETION_DATE = 'PREASBUILT ACTUAL COMPLETION DATE ';
export const FIELD_ACTUAL_COMPLETION_DATE = 'ACTUAL COMPLETION DATE';
export const FIELD_REDESIGN_COMPLETION_DATE = 'REDESIGN ACTUAL COMPLETION DATE';

export const FIELD_ASBUILT_MILES = 'ASBUILT ROUNDED MILES';
export const FIELD_DESIGN_MILES = 'DESIGN ROUNDED MILES';
export const FIELD_REDESIGN_MILES = 'REDESIGN ROUNDED MILES';

export const FIELD_DESIGN_ASSIGNEE = 'DESIGN ASSIGNEE';
export const FIELD_PREASBUILT_QC_BY = 'PREASBUILT QC BY';
export const FIELD_DESIGN_QC_BY = 'DESIGN QC BY';
export const FIELD_REDESIGN_QC_BY = 'REDESIGN QC BY';

export const HS_ACTIVE_STATUSES = ['approved', 'sent', 'redesign sent'];
